[package]
name = "miniml"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
miniml-compile = { path = "../miniml-compile" }
miniml-repl = { path = "../miniml-repl" }
miniml-syntax = { path = "../miniml-syntax" }
miniml-util = { path = "../miniml-util" }
miniml-vm = { path = "../miniml-vm" }
env_logger = "0.10.0"
insta = { version = "1.28.0", features = ["yaml"] }
clap = { version = "4.3.0", features = ["cargo", "derive"] }
rustyline = "11.0.0"
log = "0.4.18"