[workspace]

members = [
    "miniml",
    "miniml-analysis",
    "miniml-ast",
    "miniml-core",
    "miniml-infer",
    "miniml-nir",
    "miniml-parse",
    "miniml-rename",
    "miniml-tir",
    # "miniml-tree-walk",
    "miniml-utils",
]
default-members = ["miniml"]
resolver = "2"
