[workspace]

members = [
    "miniml",
    "miniml-analysis",
    "miniml-ast",
    "miniml-nir",
    # "miniml-core",
    "miniml-parse",
    "miniml-rename",
    # "miniml-tree-walk",
    "miniml-utils",
]
resolver = "2"