[workspace]
members = [
    "miniml",
    "miniml-compile",
    "miniml-hir",
    "miniml-infer",
    "miniml-lex",
    "miniml-parse",
    "miniml-rename",
    "miniml-repl",
    "miniml-runtime",
    "miniml-utils",
]
