[workspace]

members = [
    "miniml",
    "miniml-analysis",
    "miniml-ast",
    "miniml-nir",
    # "miniml-core",
    "miniml-rename",
    "miniml-syntax",
    # "miniml-tree-walk",
    "miniml-utils",
]
