@pub
@derive(Display, PartialEq)
data Vec : Nat -> Type -> Type where
  Nil  : Vec 0 a
  (::) : a -> Vec n a -> Vec (n + 1) a

@pub
length : Vec n a -> Nat
length Nil = 0
length (_ :: xs) = 1 + length xs

@pub
head : Vec (n + 1) a -> a
head (x :: _) = x

@pub
tail : Vec (n + 1) a -> Vec n a
tail (_ :: xs) = xs

@pub
map : (a -> b) -> Vec n a -> Vec n b
map _ Nil = Nil
map f (x :: xs) = f x :: map f xs

@pub
count : (p : a -> Bool) -> Vec n a -> Nat
count _ Nil = 0
count p (x :: xs)
  | p x = 1 + count p xs
  | otherwise = count p xs

@pub
filter : (p : a -> Bool) -> (v : Vec n a) -> Vec (count p v) a
filter _ Nil = Nil
filter p (x :: xs)
  | p x = x :: filter p xs
  | otherwise = filter p xs

@pub
append : Vec n a -> Vec m a -> Vec (n + m) a
append Nil ys = ys
append (x :: xs) ys = x :: append xs ys

@pub
concat : Vec n (Vec m a) -> Vec (n * m) a
concat Nil = Nil
concat (xs :: xss) = append xs (concat xss)

@pub
zip : Vec n a -> Vec n b -> Vec n (a, b)
zip Nil Nil = Nil
zip (x :: xs) (y :: ys) = (x, y) :: zip xs ys
