[package]
name = "mmc-rustbits"
version = "0.1.0"
edition = "2024"

[dependencies]
log = "0.4.18"
env_logger = "0.10.0"
insta = { version = "1.28.0", features = ["yaml"] }
itertools = "0.10.5"
logos = "0.15.0"
