-- main entry point
def main = println "Hello, world!"

-- defs
def x = 1

-- functions
fun add a b = a + b

-- let bindings
def _ = let y = 2 in add x y

-- if expressions
def _ = if x < y then x else y

-- match expressions
fun map f xs =
  match xs with
  | [] -> []
  | x :: xs -> f x :: map f xs

-- Operators
+ -- addition on a Int, Float, Integer, Rational
- -- subtraction on a Int, Float, Integer, Rational
* -- multiplication on a Int, Float, Integer, Rational
/ -- division on a Int, Float, Integer, Rational
% -- modulo on Int, Integer, Rational

-- Literals
"hello" -- String
123 -- Int
123.45 -- Float
'a' -- Char