@pub
@derive(Debug, PartialEq)
codata Stream m a =
  | Nil  : Stream m a
  | (::) : a -> m (Stream m a) -> Stream m a

@pub
class ToStream d t where
  type Elem t
  toStream :: Monad m => d -> Stream (Elem t)

@pub
class FromStream t where
  type Elem t
  fromStream :: Monad m => Stream m (Elem t) -> m t